---
title: "Lecture & Lab Materials"
author: "Andrew MacDonald"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lectures

## Unit 1: Distributions

### Class Welcome

* Recording: [Class introduction recording](https://duke.zoom.us/rec/share/uLEG-LbYlPv0NUuSLp82zpCwS9lEtVFG_GyyJzFxLrnKujZn2W4TW3pJtKrJC0ve.5C3LplqA3O6q0T8-)

### Characteristics of Distributions

* Lecture webpage: [Lecture 2: Characteristics of Distributions](https://andrewm.shinyapps.io/Lecture2-Distributions/)
* Recording: [Lecture 2 recording](https://duke.zoom.us/rec/share/NlKBUGJqr8h525mxEiyBUW6c-jLNPQ-fxNWAouso0DRBCafFNHJj8GkRpw0sDJv2.3FlH8IPcCb7hrOBp)
* Quality YouTube content: [Tidyverse music video](https://www.youtube.com/watch?v=p8Py9C8iq2s&ab_channel=TheRaf)

### Comparing distributions and the Normal distribution

* Lecture webpage: [Lecture 3: Advanced Distributions](https://andrewm.shinyapps.io/Lecture3-AdvancedDistributions/)
* Recording: [Lecture 3 recording](https://duke.zoom.us/rec/share/s8kRtcj46mXe_8_BwcYMkOa5VPXIFozXAeRQ0dlstVbypPYhF2cZXl30JeKgVwtG.xdFZSe7XM5oFafZc)

## Unit 2: Relationships Between Variables

### Association and Correlation

* Lecture webpage: [Lecture 4: Association and Correlation](https://andrewm.shinyapps.io/Lecture4-AssociationCorrelation/)
* Recording: [Lecture 4 recording](https://duke.zoom.us/rec/share/avr76S7AvD6uLcVDPBRHz9XumwKcxvWuABv8SRrXQpEQlCM-npWRQtOSuxZ6WKvW.gb_id8zOaXtKiNaS)

### Simple Linear Regression

* Lecture webpage: [Lecture 5: Simple Linear Regression](https://andrewm.shinyapps.io/Lecture5-SimpleRegression/)
* Recording: [Lecture 5 recording](https://duke.zoom.us/rec/share/9VonHtUX8D-BjkAdnUDbxYmvZAEiTp9l-KN-X4N7WeqRx_k1eg8TYrP-b4vRxirT.ILsSSCH1j1gWUBgc)

### Regression Wisdom

* Lecture webpage: [Lecture 6: Regression Wisdom](https://andrewm.shinyapps.io/Lecture6-RegressionWisdom/)
* Recording: [Lecture 6 recording](https://duke.zoom.us/rec/share/lH34CYl2MfxbzmXS08ZN59BBJgCcSTOWa_pHoq3lZlCpiGqOxgIEolLx9OxX-VQ.WkuL06zPgHNaMSjL?startTime=1631171289000)

### Multiple Regression

* Lecture webpage: [Lecture 7: Multiple Regression](https://andrewm.shinyapps.io/Lecture7-MultipleRegression/)
* Recording: [Lecture 7 recording](https://duke.zoom.us/rec/share/ohIoZnvxGiemMcANEIUN65F5i_rcfm3xuTjYVLe7HMjBGdiWiUrgZbEfgvEk7V4.Pk_3mgy_wtUdJG8o?startTime=1631534534000)

## Unit 3: Measuring Uncertainty

### Confidence Intervals - Proportions

* Lecture webpage: [Lecture 8: Confidence Intervals - Proportions](https://andrewm.shinyapps.io/Lecture8-ConfIntProportions/)
* Recording: [Lecture 8 recording](https://duke.zoom.us/rec/share/31QiaoK0Ge7XkJjONxfo1ikfpAE6QVg6QqkAJ90kkSo2qTeof0X81GXjdJ_zG7MT.WQ7iROuiWiu4oE0R?startTime=1631707519000)

### Confidence Intervals - Means

* Lecture webpage: [Lecture 9: Confidence Intervals - Means](https://andrewm.shinyapps.io/Lecture9-ConfIntMeans/)
* Recording: [Lecture 9 recording](https://duke.zoom.us/rec/share/uteUhrlCR6FAx42y5KTuy_VTeeDs0mNKOX_Cim54YEyY8aAXKo4olRiALWelDw1T.9Ilx_scw5KfPou3Z?startTime=1631876129000)

### Hypothesis Testing

* Lecture webpage: [Lecture 10: Hypothesis Testing](https://andrewm.shinyapps.io/Lecture10-HypothesisTesting/)
* Recording:

### Hypothesis Testing Wisdom

* Lecture webpage: [Lecture 11: Hypothesis Testing Wisdom](https://andrewm.shinyapps.io/Lecture11-HypothesisWisdom/)
* Recording:

## Unit 4: Statistical Inference

### Comparing Groups

* Lecture webpage:
* Recording:

### Returning to Regression

* Lecture webpage:
* Recording:

### Regression in Practice

* Lecture webpage:
* Recording:

# Labs

## Week 1: R and RMarkdown

* Lab files: [Lab 1 - R Markdown](labs/wk1/lab1.zip)
  + Make sure to extract (unzip) the lab files before attempting to modify them!

## Week 2: Association and Correlation

* Lab files: [Lab 2 - Association](labs/wk2/lab2.zip)

## Week 3: Regression Interpretation

* Lab files: [Lab 3 - Regression Interpretation](labs/wk3/lab3.zip)

## Week 4: Sampling Distribution

* Lab files [Lab 4 - Sampling Distributions](labs/wk4/lab4.zip)

## Week 5: Hypothesis Testing

* Lab files [Lab 5 - Hypothesis Testing](labs/wk5/lab5.zip)

## Week 6: $t$ tests

## Week 7: Article Analysis